/**
 * Why this file exists:
 * This component handles the rendering of both local and remote media streams.
 *
 * When it is executed:
 * Executed and updated reactively whenever a call starts, streams are acquired,
 * or tracks are added/removed.
 *
 * Which other files use it:
 * Imported and placed in the main video call layout in src/pages/Home.tsx.
 *
 * How it fits into the WebRTC signaling flow:
 * It consumes the MediaStream objects generated by getUserMedia (local) and WebRTC
 * track events (remote), binding them to HTML5 <video> elements for real-time visualization.
 */

import React, { useEffect, useRef } from "react";
import { Box, Typography, Card, Avatar } from "@mui/material";
import { Video, VideoOff, MicOff, User } from "lucide-react";


export const VideoPlayer = ({
  localStream,
  remoteStream,
  callStatus,
  activePeer,
  registeredUser,
  isVideoMuted,
  isAudioMuted,
}) => {
  const localVideoRef = useRef(null);
  const remoteVideoRef = useRef(null);

  // Bind local stream to local video tag
  useEffect(() => {
    if (localVideoRef.current && localStream) {
      localVideoRef.current.srcObject = localStream;
    }
  }, [localStream]);

  // Bind remote stream to remote video tag
  useEffect(() => {
    if (remoteVideoRef.current && remoteStream) {
      remoteVideoRef.current.srcObject = remoteStream;
    }
  }, [remoteStream]);

  const isCallConnected = callStatus === "connected";
return (
  <Box
    sx={{
      position: "relative",
      width: "100%",
      height: { xs: "60vh", md: "65vh" },
      bgcolor: "#f1f5f9",
      borderRadius: 4,
      overflow: "hidden",
      boxShadow: 1,
      border: "1px solid #e2e8f0",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    }}
  >
    {/* Remote Video */}
    {isCallConnected && remoteStream ? (
      <video
        id="remote-video"
        ref={remoteVideoRef}
        autoPlay
        playsInline
        style={{
          width: "100%",
          height: "100%",
          objectFit: "cover",
          transform: "scaleX(-1)",
          backgroundColor: "#1e293b",
        }}
      />
    ) : (
      <Box
        sx={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          textAlign: "center",
          p: 3,
          color: "text.secondary",
        }}
      >
        <Avatar
          sx={{
            width: 80,
            height: 80,
            bgcolor: "#eff6ff",
            border: "1px solid #bfdbfe",
            mb: 2,
            animation: "pulse 2s infinite",
          }}
        >
          <User size={40} color="#2563eb" />
        </Avatar>

        <Typography
          variant="h6"
          sx={{
            fontWeight: 700,
            color: "#1e293b",
          }}
        >
          {callStatus === "calling"
            ? `Calling ${activePeer?.username || "Peer"}...`
            : callStatus === "incoming"
            ? `Incoming call from ${activePeer?.username || "Peer"}`
            : "No Active Call"}
        </Typography>

        <Typography
          variant="body2"
          sx={{
            mt: 2,
            maxWidth: 350,
            color: "#64748b",
            fontSize: 14,
          }}
        >
          {callStatus === "calling"
            ? "Waiting for peer to accept the call."
            : callStatus === "incoming"
            ? "Accept the incoming call to establish connection."
            : "Select an online user from the directory list to start a clean one-to-one video call."}
        </Typography>
      </Box>
    )}

    {/* Peer Tag */}
    {isCallConnected && activePeer && (
      <Box
        sx={{
          position: "absolute",
          top: 16,
          left: 16,
          display: "flex",
          alignItems: "center",
          gap: 1,
          px: 2,
          py: 1,
          borderRadius: "999px",
          bgcolor: "rgba(255,255,255,0.9)",
          backdropFilter: "blur(10px)",
          border: "1px solid rgba(226,232,240,.7)",
          boxShadow: 1,
        }}
      >
        <Box
          sx={{
            width: 8,
            height: 8,
            borderRadius: "50%",
            bgcolor: "#22c55e",
          }}
        />

        <Typography
          variant="subtitle2"
          sx={{
            fontWeight: 700,
            fontSize: 12,
          }}
        >
          {activePeer.username}
        </Typography>
      </Box>
    )}

    {/* Local Video */}
    {localStream && (
      <Card
        id="local-video-card"
        sx={{
          position: "absolute",
          bottom: 16,
          right: 16,
          width: { xs: 128, sm: 160 },
          height: { xs: 176, sm: 224 },
          bgcolor: "#0f172a",
          border: "2px solid rgba(255,255,255,.2)",
          borderRadius: 3,
          overflow: "hidden",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          zIndex: 10,
          transition: "all .3s",
          boxShadow: 6,
        }}
      >
        {isVideoMuted ? (
          <Box
            sx={{
              width: "100%",
              height: "100%",
              bgcolor: "#1e293b",
              color: "#cbd5e1",
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              alignItems: "center",
              gap: 1,
            }}
          >
            <VideoOff size={24} />

            <Typography
              variant="caption"
              sx={{
                fontSize: 10,
                fontWeight: 700,
                textTransform: "uppercase",
                letterSpacing: 1,
              }}
            >
              Camera Off
            </Typography>
          </Box>
        ) : (
          <video
            id="local-video"
            ref={localVideoRef}
            autoPlay
            playsInline
            muted
            style={{
              width: "100%",
              height: "100%",
              objectFit: "cover",
              transform: "scaleX(-1)",
              backgroundColor: "#1e293b",
            }}
          />
        )}

        <Box
          sx={{
            position: "absolute",
            left: 8,
            right: 8,
            bottom: 8,
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            px: 1,
            py: 0.5,
            borderRadius: 1,
            bgcolor: "rgba(0,0,0,.4)",
            backdropFilter: "blur(8px)",
            color: "#fff",
          }}
        >
          <Typography
            sx={{
              fontSize: 10,
              fontWeight: 700,
              maxWidth: "60%",
              overflow: "hidden",
              textOverflow: "ellipsis",
              whiteSpace: "nowrap",
            }}
          >
            You
          </Typography>

          <Box sx={{ display: "flex", gap: 0.5 }}>
            {isAudioMuted && <MicOff size={12} color="#fb7185" />}
            {isVideoMuted && <VideoOff size={12} color="#fb7185" />}
          </Box>
        </Box>
      </Card>
    )}
  </Box>
);
};
